# Generated by Django 2.1.4 on 2018-12-19 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='catid',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
